[package]
name = "gen-i18n-html"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "3.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"